export const RESET_QUIZ = 'RESET_QUIZ';

export const FETCH_LEADERBOARD_LIST = 'FETCH_LEADERBOARD_LIST';
export const RECEIVED_LEADERBOARD_LIST = 'RECEIVED_LEADERBOARD_LIST';
export const FAILURE_LEADERBOARD_LIST = 'FAILURE_LEADERBOARD_LIST';

export const FETCH_QUIZ_LIST = 'FETCH_QUIZ_LIST';
export const RECEIVED_QUIZ_LIST = 'RECEIVED_QUIZ_LIST';
export const FAILURE_QUIZ_LIST = 'FAILURE_QUIZ_LIST';

export const FETCH_QUIZ_LEVELS = 'FETCH_QUIZ_LEVELS';
export const RECEIVED_QUIZ_LEVELS = 'RECEIVED_QUIZ_LEVELS';
export const FAILURE_QUIZ_LEVELS = 'FAILURE_QUIZ_LEVELS';

export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const RECEIVED_QUESTIONS = 'RECEIVED_QUESTIONS';
export const FAILURE_LOAD_QUESTIONS = 'FAILURE_LOAD_QUESTIONS';

export const CHECK_STATUS_ANSWER = 'CHECK_STATUS_ANSWER';
export const RECEIVED_STATUS_ANSWER = 'RECEIVED_STATUS_ANSWER';
export const FAILURE_STATUS_ANSWER = 'FAILURE_STATUS_ANSWER';
export const CLEAR_ANSWER = 'CLEAR_ANSWER';
export const RESET_ANSWERS = 'RESET_ANSWERS';

export const RESET_QUESTIONS = 'RESET_QUESTIONS';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const RESET_ACTIVE_QUESTIONS_LEVEL = 'RESET_ACTIVE_QUESTIONS_LEVEL';
export const RESET_CURRENT_QUESTION = 'RESET_CURRENT_QUESTION';

export const SET_NAV_ACTIVE = 'SET_NAV_ACTIVE';
export const CLEAR_NAV_ACTIVE = 'CLEAR_NAV_ACTIVE';

export const FETCH_LOGIN = 'FETCH_LOGIN';
export const RECEIVED_LOGIN = 'RECEIVED_LOGIN';
export const FAILURE_LOGIN = 'FAILURE_LOGIN';

export const FETCH_LOGOUT = 'FETCH_LOGOUT';
export const RECEIVED_LOGOUT = 'RECEIVED_LOGOUT';
export const FAILURE_LOGOUT = 'FAILURE_LOGOUT';

export const ADD_POINTS = 'ADD_POINTS';
export const RECEIVED_ADD_POINTS = 'RECEIVED_ADD_POINTS';
export const FAILURE_ADD_POINTS = 'FAILURE_ADD_POINTS';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const ADD_LOADER = 'ADD_LOADER';
export const REMOVE_LOADER = 'REMOVE_LOADER';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';
