export const START_QUIZ = 'START_QUIZ';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const RESET_QUIZ = 'RESET_QUIZ';

export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const RECEIVED_QUESTIONS = 'RECEIVED_QUESTIONS';
export const FAILURE_LOAD_QUESTIONS = 'FAILURE_LOAD_QUESTIONS';

export const CHECK_STATUS_ANSWER = 'CHECK_STATUS_ANSWER';
export const RECEIVED_STATUS_ANSWER = 'RECEIVED_STATUS_ANSWER';
export const FAILURE_STATUS_ANSWER = 'FAILURE_STATUS_ANSWER';

export const RESET_QUESTIONS = 'RESET_QUESTIONS';
export const NEXT_QUESTION = 'NEXT_QUESTION';

export const CLEAR_ANSWER = 'CLEAR_ANSWER';
